### ISSUE TITLE
Can we get an edit link?

### ISSUE THREAD

**Issue by coolaj86** [ryanburnette/eon#2]
Maybe either up at the top near the updated at date, or down at the bottom?

I want to be able to edit posts more quickly!

**Comment by ryanburnette** [comment]
How about a secret keystroke like "edit" and then the link appears?

**Comment by coolaj86** [comment]
“Suggest Edit” at the top right.

but there needs to be a way to disable it for private repos.

**Comment by ryanburnette** [comment]
I'll make it something you turn on in the site params. Will do soon.

**Comment by ryanburnette** [comment]
#16
