### ISSUE TITLE
make sure minified output is .min.css or .min.js

### ISSUE THREAD

**Issue by ryanburnette** [ryanburnette/eon#3]
Suggested by @coolaj86

**Comment by ryanburnette** [comment]
The reason I haven't done this before is because I don't want to have to add anything to my layouts that determines whether style.css or style.min.css should be used. The min.css extension is just a convention and it's one I don't care to use.

Would .ignore static/**.css work for you?

**Comment by coolaj86** [comment]
But wouldn't I want to put my own styles in `static/`? Isn't that where all static content that's copied to the root of `public/` go?

**Comment by coolaj86** [comment]
Maybe that could be done as part of how dist-hash replaces the files?

**Comment by ryanburnette** [comment]
I'm closing because I don't see a change I plan to make, but I'm happy to re-open if it needs more discussion.
